import { HttpStatus } from '@nestjs/common';

/**
 * Canonical API error codes. Adding a code here without an HTTP status
 * in ERROR_HTTP_STATUS is a compile error (`satisfies Record<ErrorCode, ...>`).
 */
export const ERROR_CODES = [
  'BAD_REQUEST',
  'VALIDATION_ERROR',
  'UNAUTHORIZED',
  'INVALID_CREDENTIALS',
  'TOKEN_EXPIRED',
  'TOKEN_INVALID',
  'FORBIDDEN',
  'GUEST_NOT_ALLOWED',
  'EMAIL_NOT_VERIFIED',
  'NOT_FOUND',
  'CONFLICT',
  'ALREADY_EXISTS',
  'EMAIL_ALREADY_REGISTERED',
  'PAYLOAD_TOO_LARGE',
  'UNPROCESSABLE_ENTITY',
  'INVALID_OTP',
  'OTP_EXPIRED',
  'OTP_TOO_MANY_ATTEMPTS',
  'INVALID_RESET_TOKEN',
  'RATE_LIMITED',
  'OTP_RESEND_COOLDOWN',
  'INTERNAL_ERROR',
  'NOT_IMPLEMENTED',
  'SERVICE_UNAVAILABLE',
  'GATEWAY_TIMEOUT',
  'PRICES_INCOMPLETE',
  'BILL_LOCKED',
  'NOT_IN_PAYMENT',
  'CLAIM_NOT_PENDING',
  'ALREADY_PAID',
  'CANNOT_CLAIM_AS_HOST',
  'SETTLEMENT_INCOMPLETE',
  'LOBBY_SETTLED',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const ERROR_HTTP_STATUS = {
  BAD_REQUEST: HttpStatus.BAD_REQUEST,
  VALIDATION_ERROR: HttpStatus.UNPROCESSABLE_ENTITY,
  UNAUTHORIZED: HttpStatus.UNAUTHORIZED,
  INVALID_CREDENTIALS: HttpStatus.UNAUTHORIZED,
  TOKEN_EXPIRED: HttpStatus.UNAUTHORIZED,
  TOKEN_INVALID: HttpStatus.UNAUTHORIZED,
  FORBIDDEN: HttpStatus.FORBIDDEN,
  GUEST_NOT_ALLOWED: HttpStatus.FORBIDDEN,
  EMAIL_NOT_VERIFIED: HttpStatus.FORBIDDEN,
  NOT_FOUND: HttpStatus.NOT_FOUND,
  CONFLICT: HttpStatus.CONFLICT,
  ALREADY_EXISTS: HttpStatus.CONFLICT,
  EMAIL_ALREADY_REGISTERED: HttpStatus.CONFLICT,
  PAYLOAD_TOO_LARGE: HttpStatus.PAYLOAD_TOO_LARGE,
  UNPROCESSABLE_ENTITY: HttpStatus.UNPROCESSABLE_ENTITY,
  INVALID_OTP: HttpStatus.UNPROCESSABLE_ENTITY,
  OTP_EXPIRED: HttpStatus.UNPROCESSABLE_ENTITY,
  OTP_TOO_MANY_ATTEMPTS: HttpStatus.UNPROCESSABLE_ENTITY,
  INVALID_RESET_TOKEN: HttpStatus.UNPROCESSABLE_ENTITY,
  RATE_LIMITED: HttpStatus.TOO_MANY_REQUESTS,
  OTP_RESEND_COOLDOWN: HttpStatus.TOO_MANY_REQUESTS,
  INTERNAL_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  NOT_IMPLEMENTED: HttpStatus.NOT_IMPLEMENTED,
  SERVICE_UNAVAILABLE: HttpStatus.SERVICE_UNAVAILABLE,
  GATEWAY_TIMEOUT: HttpStatus.GATEWAY_TIMEOUT,
  PRICES_INCOMPLETE: HttpStatus.UNPROCESSABLE_ENTITY,
  BILL_LOCKED: HttpStatus.CONFLICT,
  NOT_IN_PAYMENT: HttpStatus.CONFLICT,
  CLAIM_NOT_PENDING: HttpStatus.CONFLICT,
  ALREADY_PAID: HttpStatus.CONFLICT,
  CANNOT_CLAIM_AS_HOST: HttpStatus.FORBIDDEN,
  SETTLEMENT_INCOMPLETE: HttpStatus.CONFLICT,
  LOBBY_SETTLED: HttpStatus.CONFLICT,
} as const satisfies Record<ErrorCode, number>;

export type ErrorHttpStatus = (typeof ERROR_HTTP_STATUS)[ErrorCode];

const HTTP_STATUS_TO_CODE: Partial<Record<number, ErrorCode>> = {
  [HttpStatus.BAD_REQUEST]: 'BAD_REQUEST',
  [HttpStatus.UNAUTHORIZED]: 'UNAUTHORIZED',
  [HttpStatus.FORBIDDEN]: 'FORBIDDEN',
  [HttpStatus.NOT_FOUND]: 'NOT_FOUND',
  [HttpStatus.CONFLICT]: 'CONFLICT',
  [HttpStatus.PAYLOAD_TOO_LARGE]: 'PAYLOAD_TOO_LARGE',
  [HttpStatus.UNPROCESSABLE_ENTITY]: 'UNPROCESSABLE_ENTITY',
  [HttpStatus.TOO_MANY_REQUESTS]: 'RATE_LIMITED',
  [HttpStatus.INTERNAL_SERVER_ERROR]: 'INTERNAL_ERROR',
  [HttpStatus.NOT_IMPLEMENTED]: 'NOT_IMPLEMENTED',
  [HttpStatus.SERVICE_UNAVAILABLE]: 'SERVICE_UNAVAILABLE',
  [HttpStatus.GATEWAY_TIMEOUT]: 'GATEWAY_TIMEOUT',
};

export function errorCodeFromHttpStatus(status: number): ErrorCode {
  return HTTP_STATUS_TO_CODE[status] ?? 'INTERNAL_ERROR';
}
